name: HTTP request
description: Make an HTTP request to a URL

branding:
  icon: cloud
  color: blue

inputs:
  url:
    description: Request URL
    required: true
  method:
    description: Request method
    default: GET
  headers:
    description: Request headers
  body:
    description: Request body
  retry-count:
    description: Number of times to retry if the response is not successful
    default: 0
  retry-delay:
    description: Delay between retries in milliseconds
    default: 1000
  fail-on-error:
    description: Fail the step if the response is not successful
    default: true

outputs:
  status:
    description: Response status code
  headers:
    description: Response headers
  body:
    description: Response body

runs:
  using: node16
  main: dist/index.js
