name: Send HTTP Request
description: Make an HTTP request to a URL

branding:
  icon: cloud
  color: blue

inputs:
  url:
    description: URL to send the request to
    required: true
  method:
    description: HTTP method to use
    default: GET
  headers:
    description: Headers to send with the request (one per line)
  body:
    description: Body to send with the request
  retry-count:
    description: Number of times to retry on unsuccessful requests
    default: 0
  retry-delay:
    description: Delay between retries in milliseconds
    default: 1000
  fail-on-error:
    description: Whether to fail the step if the request was unsuccessful
    default: true

outputs:
  status:
    description: Status code of the response
  success:
    description: Whether the response status code indicates success
  headers:
    description: Headers returned by the response (formatted as a JSON object)
  body:
    description: Body of the response

runs:
  using: node20
  main: dist/index.js
